image:
  file: .gitpod.dockerfile

ports:
  - port: 19000-19002

tasks:
  - before: |
      echo "Setup Java 8..."
      sdk install java 8.0.292-open
      sdk default java 8.0.292-open

      echo "Installing Android SDK..."
      mkdir -p /workspace/android-sdk && cd /workspace/android-sdk && wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip && unzip commandlinetools-linux-7302050_latest.zip && rm commandlinetools-linux-7302050_latest.zip     

      /workspace/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/workspace/android-sdk "platform-tools" "platforms;android-28" "build-tools;28.0.3" "system-images;android-28;google_apis;x86"

      export ANDROID_HOME=/workspace/android-sdk
      export PATH=$PATH:$ANDROID_HOME/emulator
      export PATH=$PATH:$ANDROID_HOME/tools
      export PATH=$PATH:$ANDROID_HOME/tools/bin
      export PATH=$PATH:$ANDROID_HOME/platform-tools

      avdmanager create avd --force --name testAVD --abi google_apis/x86 --package "system-images;android-28;google_apis;x86"
      
      echo "Installing npm dependencies..."
      npm install
      cd /workspace/hyperhyper/
      expo doctor
    command: |
      npm start